apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-pvc
spec:
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi