ibm-cp4sthreatmanagements-instance:
  metadata:
    name: threatmgmt
  spec:
    acceptLicense: true
    basicDeploymentConfiguration:
      adminUser: admin
      domain: ''
      storageClass: ocs-storagecluster-cephfs
    extendedDeploymentConfiguration:
      airgapInstall: false
      backupStorageClass: ocs-storagecluster-cephfs
      backupStorageSize: ''
      imagePullPolicy: IfNotPresent
      repository: cp.icr.io/cp/cp4s
      repositoryType: entitled
      roksAuthentication: false
    threatManagementCapabilities:
      deployDRC: true
      deployRiskManager: true
      deployThreatInvestigator: true